### PR TITLE
Add filament start/end g-code for pressure advance and retraction

### PR DESCRIPTION
**Pull request by ProfDrYoMan**

### CODE REVIEW

**Comment by halfmanbear** [comment]
I'm currently testing a slight variation of the method mentioned by `dasky` over on the Discord Channel.

I'll remove the `Firmware Retraction Config` section from the end of the `printer.cfg` and place the default include enable with the others at the top of the `printer.cfg`.
  
Screenshot 2024-03-20 at 12 54 49

I'll update the OrcaSlicer filament profiles to enable our defaults within the 'Setting Overrides' tab.
  
Screenshot 2024-03-20 at 13 13 53

The following `Filament Start G-code` allows parsing of the Slicers Filament 'Setting Overrides'
  
Screenshot 2024-03-20 at 13 13 45

**Comment by halfmanbear** [comment]
I'm currently looking at handking pressure advance. It seems that OrcaSlicer directly transfers the value from the filament profile to Klipper, provided that this feature is activated.

Screenshot 2024-03-20 at 14 21 44


I'll adjust the filament profiles to include the default value specified in the `printer.cfg`. Additionally, I'll update the Wiki to inform users that filament-specific tuning values are now managed through the slicer's filament-specific profiles.

**Comment by ProfDrYoMan** [comment]
Will check if this is also possible in Prusa Slicer. 
If yes, this looks good.

**Comment by ProfDrYoMan** [comment]
For pressure advance this is not existing in Prusa. I am pretty sure but will recheck. 

I would not suggest changes that force ppl to use one slicer.

**Comment by ProfDrYoMan** [comment]
And what if ppl are not adding this to the filament code? There should be a fallback.

**Comment by halfmanbear** [comment]
Good points I can add;

SET_PRESSURE_ADVANCE ADVANCE=x to prusa slicer filament start gcode in the wiki.

I don't want to load the printer.cfg with too much workaround code. I've always stated the project is only fully supported with OrcaSlicer as I don't have the free time to create and maintain multiple slicer profiles for various slicers. Additionally helping users troubleshoot is almost impossible if they are using another slicer (100s of variables).

As prusa is very close to orca it isn't too hard to add functionality support here. I will update the "using other slicers" wiki page with more details to get prusaslocer fully operational with this project but I won't be personally creating and maintaining profiles.

**Comment by ProfDrYoMan** [comment]
> I'm currently testing a slight variation of the method mentioned by `dasky` over on the Discord Channel.
> 
> I'll remove the `Firmware Retraction Config` section from the end of the `printer.cfg` and place the default include enable with the others at the top of the `printer.cfg`.
> 
> Screenshot 2024-03-20 at 12 54 49
> I'll update the OrcaSlicer filament profiles to enable our defaults within the 'Setting Overrides' tab.
> 
> Screenshot 2024-03-20 at 13 13 53
> The following `Filament Start G-code` allows parsing of the Slicers Filament 'Setting Overrides'
> 
> Screenshot 2024-03-20 at 13 13 45

For this one. Prusa got this covered:
image

I would argue to make ALL options pushed thru in the filament start g-code.

**Comment by ProfDrYoMan** [comment]
> I'm currently looking at handking pressure advance. It seems that OrcaSlicer directly transfers the value from the filament profile to Klipper, provided that this feature is activated.
> 
> Screenshot 2024-03-20 at 14 21 44
> I'll adjust the filament profiles to include the default value specified in the `printer.cfg`. Additionally, I'll update the Wiki to inform users that filament-specific tuning values are now managed through the slicer's filament-specific profiles.

This one is not available in Prusa, but it is ok to use the suggested filament start g-code.

**Comment by ProfDrYoMan** [comment]
One thing that your solution lacks:

The printer is not configure back to defaults!
If somebody is printing with a material where not all options are set, ... well the last ones of the last material will be used.

**Comment by halfmanbear** [comment]
I've decided to disable pressure advanced on orca to standardise this in the slicer filament start gcode should work for all slicers.

`SET_PRESSURE_ADVANCE ADVANCE=0.02725 SMOOTH_TIME=0.02`

**Comment by ProfDrYoMan** [comment]
Ok. so no going back to default. Do you implement and drop this one?
You should think about enabling all retraction overwrites, since it does not make a difference on the start g-code.

**Comment by ProfDrYoMan** [comment]
Here is the g-code for prusa slicer. It's more complex than expected since it needs to take care that not all variables are set

```SET_PRESSURE_ADVANCE ADVANCE=0.03 SMOOTH_TIME=0.02
{if !is_nil(filament_retract_length[current_extruder]) or !is_nil(filament_retract_speed[current_extruder]) or !is_nil(filament_retract_restart_extra[current_extruder])or !is_nil(filament_deretract_speed[current_extruder])}SET_RETRACTION{endif}{if !is_nil(filament_retract_length[current_extruder])} RETRACT_LENGTH=[filament_retract_length[current_extruder]]{endif}{if !is_nil(filament_retract_speed[current_extruder])} RETRACT_SPEED=[filament_retract_speed[current_extruder]]{endif}{if !is_nil(filament_retract_restart_extra[current_extruder])} UNRETRACT_EXTRA_LENGTH=[filament_retract_restart_extra[current_extruder]]{endif}{if !is_nil(filament_deretract_speed[current_extruder])} UNRETRACT_SPEED=[filament_deretract_speed[current_extruder]]{endif}
```

**Comment by halfmanbear** [comment]
Don't drop this, I'll make some changes, merge then I'll add some more stuff tomorrow 👍

**Comment by halfmanbear** [comment]
> Here is the g-code for prusa slicer. It's more complex than expected since it needs to take care that not all variables are set
> 
> ```
> SET_PRESSURE_ADVANCE ADVANCE=0.03 SMOOTH_TIME=0.02
> {if !is_nil(filament_retract_length[current_extruder]) or !is_nil(filament_retract_speed[current_extruder]) or !is_nil(filament_retract_restart_extra[current_extruder])or !is_nil(filament_deretract_speed[current_extruder])}SET_RETRACTION{endif}{if !is_nil(filament_retract_length[current_extruder])} RETRACT_LENGTH=[filament_retract_length[current_extruder]]{endif}{if !is_nil(filament_retract_speed[current_extruder])} RETRACT_SPEED=[filament_retract_speed[current_extruder]]{endif}{if !is_nil(filament_retract_restart_extra[current_extruder])} UNRETRACT_EXTRA_LENGTH=[filament_retract_restart_extra[current_extruder]]{endif}{if !is_nil(filament_deretract_speed[current_extruder])} UNRETRACT_SPEED=[filament_deretract_speed[current_extruder]]{endif}
> ```

I have [firmware_retraction] still enabled so if the slicer doesn't provide any values it uses klippers defaults

**Comment by ProfDrYoMan** [comment]
Ok for pressure advance this works.

I was just talking about the long g-code with lots of conditions for retraction.
This is needed because if someone does not set an overwrite the generated g-code is wrong if you do it the simple way.
image

**Comment by halfmanbear** [comment]
Do you have firmware retraction enabled?

Screenshot-2023-08-09-at-23 01 16-600x342

**Comment by ProfDrYoMan** [comment]
Yes for sure, why?

**Comment by halfmanbear** [comment]
Klipper will ignore any slicer retraction settings in gcode. Except from the ones explicitly parsed with SET_RETRACTION

**Comment by ProfDrYoMan** [comment]
Please check the "funny G-Code above". The: "{if !is_nil(filament_retract_length[current_extruder]) or !is_nil(...."

You will see this will expand to a valid SET_RETRACTION in all cases.

This is needed!
Otherwise there will be a invalid SET_RETRACTION line generated when ppl do not set all filament overwrites.

Result could be something like:
SET_RETRACTION  RETRACT_LENGTH= RETRACT_SPEED= UNRETRACT_EXTRA_LENGTH= UNRETRACT_SPEED=

And this is clearly a syntax error.

**Comment by halfmanbear** [comment]
Oh I see what you mean! Yes but the instructions will be clear in the wiki for running retraction. If they aren't set they will rightfully be presented an error.

**Comment by ProfDrYoMan** [comment]
But why forcing the user to set all variables when you can just solve it with the g-code above?
You are right, it might introduce issues because if a variable is not set, it will not get overwritten. => Chaos.

**Comment by halfmanbear** [comment]
If they have not read the wiki to get our filament start code then they won't get any errors. If they have read it and pasted the filament start code they would have read they need to set the prams. But I will pre-populate all the orca profiles with default values so it's ready to go

**Comment by ProfDrYoMan** [comment]
Yep. So this is what is needed.

```
SET_RETRACTION RETRACT_LENGTH=[filament_retract_length[current_extruder]] RETRACT_SPEED=[filament_retract_speed[current_extruder]] UNRETRACT_EXTRA_LENGTH=[filament_retract_restart_extra[current_extruder]] UNRETRACT_SPEED=[filament_deretract_speed[current_extruder]]
```

**Comment by halfmanbear** [comment]
I'll add that to the other slicers config page 👍

**Pull request merged**
