### PR TITLE
Dev to Main

### PR DESCRIPTION
**Pull request by halfmanbear**
Fix for MCU errors: re-run opennept4une installer script option `4) Update MCU & Virtual MCU Firmware`

Improved inductive bed probe accuracy (All models)

N4Pro: Outer bed auto on if centre bed temp is ≥ 90°C

Webcam script update (multiple cameras is still work In progress)

### CODE REVIEW

**Review by barrenechea — APPROVED** [review]
GTM! 🚀

**Comment by peperonikiller** [comment]
Thank you guys for all the work you do for us Neptune owners!!!

**Comment by IsakJetbean** [comment]
Thank you for continuing to support the Neptune printers!  I had to ask, but I'm curious if ya'll are working on a way to make Speed Adaptive Mode work?  It's the one feature that I miss from stock that I can't enable on ON4

**Comment by halfmanbear** [comment]
> Thank you for continuing to support the Neptune printers! I hate to ask, but I'm curious if ya'll are working on a way to make Speed Adaptive Mode work? It's the one feature that I miss from stock that I can't enable on ON4

Best place for this feature is going to within the slicers gcode at layer change. Some discussions linked below talk about solutions, prusa and orca typically share similar command structure.

https://www.reddit.com/r/OrcaSlicer/comments/1ex289l/comment/lj4vfgd/

https://github.com/prusa3d/PrusaSlicer/issues/11292

**Pull request merged**
