### PR TITLE
generate printer configs from one base file

### PR DESCRIPTION
**Pull request by phillipthelen**
From what I can tell this generates printer config files that are the same as the ones we currently have in all important parts.
Some minor things like whitespace and formatting is now unified and because of that different when diffing the configs.

each printer now has one main config file (p.e. `n4.cfg`) that has a list of variables that are replaced in the base config. There are also config files `section_X.cfg`, that replace mutiline blocks. This adds a bunch of new files, but makes it very easy to manage the different printer models.

It is not integrated yet with opennept4une.sh, because I would like some feedback first and some other people checking that the generated config files are correct

### CODE REVIEW

**Comment by barrenechea** [comment]
Ok, I had to checkout this branch to do some E2E 😄  I generated an N4 0.8A profile:

- `Bed_Level_Screws_Tune` no longer heats the bed. Intended change? It may be unrelated to this PR's title
- Shouldn't the `{{ extra_heating }}` section be in the `Macros` section of the config instead of the end?

And a maybe opinionated take:
- The new `extra_heating` macros look a bit redundant, not much different between `SET_HEATER_TEMPERATURE` to the stock `SET_HEATER_TEMPERATURE`, similar to the WAIT macro. I may be missing something?

Other than that, the generated `output.cfg` adds some spacing where needed, and keeps the same config settings to the stock `n4-0.8-printer.cfg` file! Awesome job 🚀

**Comment by phillipthelen** [comment]
> Ok, I had to checkout this branch to do some E2E 😄 I generated an N4 0.8A profile:
> 
> * `Bed_Level_Screws_Tune` no longer heats the bed. Intended change? It may be unrelated to this PR's title

Intended but you're right it's not exactly related. We had talked about the change in discord and since I had to change the handling of setting that heater anyway, I chose to just remove it

> * Shouldn't the `{{ extra_heating }}` section be in the `Macros` section of the config instead of the end?

I put it at the end, because that's where the N4Pro config had it. I could move it though.
> 
> And a maybe opinionated take:
> 
> * The new `extra_heating` macros look a bit redundant, not much different between `SET_BED_TEMPERATURE` to the stock `SET_HEATER_TEMPERATURE`, similar to the WAIT macro. I may be missing something?

that is true. For the non-pro models it's kind of redundant. I did it this way, because the pro model needs the special macros for setting the bed temperature. So the SET_BED_TEMPERATURE macro is mostly a compatibility macro to make the call the same between all models

> Other than that, the generated `output.cfg` adds some spacing where needed, and keeps the same config settings to the stock `n4-0.8-printer.cfg` file! Awesome job 🚀

awesome!

**Comment by halfmanbear** [comment]
I already removed the turn off heaters in the bed screws tune section.

https://github.com/OpenNeptune3D/OpenNept4une/pull/115

The additional bed heating section was a community request to enable users to have a diff bed temperature at the start of a print for the initial layer adhesion then to lower it after.

**Comment by halfmanbear** [comment]
From what I can tell the following can be/are the same across all variants.
We could remove these as variables and hard-code them into the base.cfg?

```
max_accel=3100

x_dir_pin=PC13

x_enable_pin=!PC15

z_step_pin=PC10

z_enable_pin=!PC11

z_endstop_pin=probe:z_virtual_endstop

extruder_rotation_distance=28.888

bed_max_temp=120

probe_z_offset=0.650

pressure_advance=0.02725

bed_mesh_min=10,21

```

**Comment by halfmanbear** [comment]
This should now create working printer.cfg's for all models from the OpenNept4une.sh

I had some path issues with running the script from ~/ so changed generate_conf.py paths to use os.path.
Removed any non-applicable section_files
and some layout/continuity improvements between all confs

**Comment by halfmanbear** [comment]
Ok, the config update process now preserves the users;`#*# <--- SAVE_CONFIG --->` section in their printer.cfg
Users should be able to upgrade their printer.cfg without transferring or re-tuning any of the following.

[bed_mesh] any user saved meshes
[heater_bed] /  [heater_bed_outer] & [extruder] user-tuned PID values
[axis_twist_compensation] user-tuned value
[probe] user-tuned z_offset value

I have also done some layout changes to clean the configs up. 
Let me know if you have any suggestions for improvement here

**Pull request merged**
